// <auto-generated />
using CodeFirstPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4Point1_EF.Migrations
{
    [DbContext(typeof(ShelfContext))]
    [Migration("20200921154253_ShelfSeed")]
    partial class ShelfSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstPractice.Models.Shelf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<int>("MaterialID")
                        .HasColumnName("material_id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.HasIndex("MaterialID")
                        .HasName("FK_Shelf_ShelfMaterial");

                    b.ToTable("shelf");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            MaterialID = -2,
                            Name = "Tools Shelf"
                        },
                        new
                        {
                            ID = -2,
                            MaterialID = -3,
                            Name = "Electronics Shelf"
                        },
                        new
                        {
                            ID = -3,
                            MaterialID = -1,
                            Name = "Food Shelf"
                        },
                        new
                        {
                            ID = -4,
                            MaterialID = -1,
                            Name = "Dishes Shelf"
                        },
                        new
                        {
                            ID = -5,
                            MaterialID = -1,
                            Name = "Book Shelf"
                        },
                        new
                        {
                            ID = -6,
                            MaterialID = -1,
                            Name = "Plant Shelf"
                        },
                        new
                        {
                            ID = -7,
                            MaterialID = -1,
                            Name = "Cactus Shelf"
                        },
                        new
                        {
                            ID = -8,
                            MaterialID = -3,
                            Name = "Pet Food Shelf"
                        },
                        new
                        {
                            ID = -9,
                            MaterialID = -3,
                            Name = "Lego Shelf"
                        },
                        new
                        {
                            ID = -10,
                            MaterialID = -1,
                            Name = "Magazine Shelf"
                        });
                });

            modelBuilder.Entity("CodeFirstPractice.Models.ShelfMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(25)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("shelfmaterial");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            MaterialName = "Wood"
                        },
                        new
                        {
                            ID = -2,
                            MaterialName = "Steel"
                        },
                        new
                        {
                            ID = -3,
                            MaterialName = "Plastic"
                        });
                });

            modelBuilder.Entity("CodeFirstPractice.Models.Shelf", b =>
                {
                    b.HasOne("CodeFirstPractice.Models.ShelfMaterial", "Material")
                        .WithMany("Shelves")
                        .HasForeignKey("MaterialID")
                        .HasConstraintName("FK_Shelf_ShelfMaterial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
