// <auto-generated />
using CodeFirstPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4Point1_EF.Migrations
{
    [DbContext(typeof(ShelfContext))]
    [Migration("20200921151016_ShelvesToShelf")]
    partial class ShelvesToShelf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstPractice.Models.Shelf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("shelf");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Tools Shelf"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Electronics Shelf"
                        },
                        new
                        {
                            ID = -3,
                            Name = "Food Shelf"
                        },
                        new
                        {
                            ID = -4,
                            Name = "Dishes Shelf"
                        },
                        new
                        {
                            ID = -5,
                            Name = "Book Shelf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
