// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4Point1_EF.Models;

namespace _4Point1_EF.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200918174152_LastNames")]
    partial class LastNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_4Point1_EF.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("dateofbirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("enddate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<DateTime>("HireDate")
                        .HasColumnName("hiredate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("LocationID")
                        .HasColumnName("location_id")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("LocationID")
                        .HasName("FK_Employee_Location");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DateOfBirth = new DateTime(1972, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Betty",
                            HireDate = new DateTime(2004, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Foster",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -2,
                            DateOfBirth = new DateTime(1961, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michelle",
                            HireDate = new DateTime(2008, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richardson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -3,
                            DateOfBirth = new DateTime(1959, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eric",
                            HireDate = new DateTime(2001, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kelly",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -4,
                            DateOfBirth = new DateTime(1968, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vincent",
                            HireDate = new DateTime(2006, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "King",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -5,
                            DateOfBirth = new DateTime(1958, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julia",
                            HireDate = new DateTime(2008, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -6,
                            DateOfBirth = new DateTime(1974, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Virginia",
                            HireDate = new DateTime(2012, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wright",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -7,
                            DateOfBirth = new DateTime(1966, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexis",
                            HireDate = new DateTime(2004, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Baker",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -8,
                            DateOfBirth = new DateTime(1965, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julia",
                            HireDate = new DateTime(2001, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -9,
                            DateOfBirth = new DateTime(1972, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Martha",
                            HireDate = new DateTime(2001, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rivera",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -10,
                            DateOfBirth = new DateTime(1964, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Debra",
                            HireDate = new DateTime(2007, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nelson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -11,
                            DateOfBirth = new DateTime(1967, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jordan",
                            HireDate = new DateTime(2009, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -12,
                            DateOfBirth = new DateTime(1978, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sean",
                            HireDate = new DateTime(2008, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanchez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -13,
                            DateOfBirth = new DateTime(1964, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Walter",
                            HireDate = new DateTime(2004, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nelson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -14,
                            DateOfBirth = new DateTime(1975, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Willie",
                            HireDate = new DateTime(2014, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roberts",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -15,
                            DateOfBirth = new DateTime(1964, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Noah",
                            HireDate = new DateTime(2008, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morales",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -16,
                            DateOfBirth = new DateTime(1964, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arthur",
                            HireDate = new DateTime(2006, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -17,
                            DateOfBirth = new DateTime(1968, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ralph",
                            HireDate = new DateTime(2007, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reed",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -18,
                            DateOfBirth = new DateTime(1962, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anthony",
                            HireDate = new DateTime(2010, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Adams",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -19,
                            DateOfBirth = new DateTime(1973, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rebecca",
                            HireDate = new DateTime(2003, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -20,
                            DateOfBirth = new DateTime(1951, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Barbara",
                            HireDate = new DateTime(2009, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -21,
                            DateOfBirth = new DateTime(1977, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HireDate = new DateTime(2014, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -22,
                            DateOfBirth = new DateTime(1973, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Philip",
                            HireDate = new DateTime(2014, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -23,
                            DateOfBirth = new DateTime(1980, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            HireDate = new DateTime(2009, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -24,
                            DateOfBirth = new DateTime(1950, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Angela",
                            HireDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -25,
                            DateOfBirth = new DateTime(1954, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eugene",
                            HireDate = new DateTime(2001, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wood",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -26,
                            DateOfBirth = new DateTime(1972, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Angela",
                            HireDate = new DateTime(2014, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Price",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -27,
                            DateOfBirth = new DateTime(1951, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kimberly",
                            HireDate = new DateTime(2001, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richardson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -28,
                            DateOfBirth = new DateTime(1974, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Wayne",
                            HireDate = new DateTime(2010, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -29,
                            DateOfBirth = new DateTime(1973, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marilyn",
                            HireDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hughes",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -30,
                            DateOfBirth = new DateTime(1970, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diane",
                            HireDate = new DateTime(2002, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roberts",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -31,
                            DateOfBirth = new DateTime(1959, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Wayne",
                            HireDate = new DateTime(2013, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kelly",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -32,
                            DateOfBirth = new DateTime(1952, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cheryl",
                            HireDate = new DateTime(2011, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morris",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -33,
                            DateOfBirth = new DateTime(1960, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Patrick",
                            HireDate = new DateTime(2004, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -34,
                            DateOfBirth = new DateTime(1956, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            HireDate = new DateTime(2009, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Green",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -35,
                            DateOfBirth = new DateTime(1954, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Larry",
                            HireDate = new DateTime(2010, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gray",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -36,
                            DateOfBirth = new DateTime(1957, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carolyn",
                            HireDate = new DateTime(2001, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hill",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -37,
                            DateOfBirth = new DateTime(1961, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roy",
                            HireDate = new DateTime(2008, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thompson",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -38,
                            DateOfBirth = new DateTime(1974, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kathryn",
                            HireDate = new DateTime(2006, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -39,
                            DateOfBirth = new DateTime(1965, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Theresa",
                            HireDate = new DateTime(2013, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Myers",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -40,
                            DateOfBirth = new DateTime(1979, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cynthia",
                            HireDate = new DateTime(2002, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mendoza",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -41,
                            DateOfBirth = new DateTime(1957, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gregory",
                            HireDate = new DateTime(2012, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -42,
                            DateOfBirth = new DateTime(1952, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carolyn",
                            HireDate = new DateTime(2013, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -43,
                            DateOfBirth = new DateTime(1964, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            HireDate = new DateTime(2014, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harris",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -44,
                            DateOfBirth = new DateTime(1960, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Betty",
                            HireDate = new DateTime(2011, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Miller",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -45,
                            DateOfBirth = new DateTime(1974, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Aaron",
                            HireDate = new DateTime(2008, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Baker",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -46,
                            DateOfBirth = new DateTime(1951, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nancy",
                            HireDate = new DateTime(2008, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -47,
                            DateOfBirth = new DateTime(1968, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            HireDate = new DateTime(2013, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bailey",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -48,
                            DateOfBirth = new DateTime(1953, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Wayne",
                            HireDate = new DateTime(2004, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kim",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -49,
                            DateOfBirth = new DateTime(1952, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mary",
                            HireDate = new DateTime(2012, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richardson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -50,
                            DateOfBirth = new DateTime(1955, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            HireDate = new DateTime(2012, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -51,
                            DateOfBirth = new DateTime(1954, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charlotte",
                            HireDate = new DateTime(2005, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -52,
                            DateOfBirth = new DateTime(1974, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            HireDate = new DateTime(2007, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peterson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -53,
                            DateOfBirth = new DateTime(1957, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dorothy",
                            HireDate = new DateTime(2008, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Robinson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -54,
                            DateOfBirth = new DateTime(1954, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            HireDate = new DateTime(2011, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Phillips",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -55,
                            DateOfBirth = new DateTime(1959, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kayla",
                            HireDate = new DateTime(2000, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -56,
                            DateOfBirth = new DateTime(1966, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Abigail",
                            HireDate = new DateTime(2000, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edwards",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -57,
                            DateOfBirth = new DateTime(1965, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Karen",
                            HireDate = new DateTime(2005, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "King",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -58,
                            DateOfBirth = new DateTime(1955, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Richard",
                            HireDate = new DateTime(2006, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cooper",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -59,
                            DateOfBirth = new DateTime(1971, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Evelyn",
                            HireDate = new DateTime(2000, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kim",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -60,
                            DateOfBirth = new DateTime(1970, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sharon",
                            HireDate = new DateTime(2000, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Turner",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -61,
                            DateOfBirth = new DateTime(1956, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gerald",
                            HireDate = new DateTime(2001, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -62,
                            DateOfBirth = new DateTime(1974, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            HireDate = new DateTime(2004, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patel",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -63,
                            DateOfBirth = new DateTime(1956, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gerald",
                            HireDate = new DateTime(2010, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Howard",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -64,
                            DateOfBirth = new DateTime(1955, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elizabeth",
                            HireDate = new DateTime(2002, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Adams",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -65,
                            DateOfBirth = new DateTime(1971, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Justin",
                            HireDate = new DateTime(2007, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cooper",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -66,
                            DateOfBirth = new DateTime(1968, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julia",
                            HireDate = new DateTime(2012, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -67,
                            DateOfBirth = new DateTime(1968, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pamela",
                            HireDate = new DateTime(2004, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -68,
                            DateOfBirth = new DateTime(1958, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Katherine",
                            HireDate = new DateTime(2008, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -69,
                            DateOfBirth = new DateTime(1977, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Abigail",
                            HireDate = new DateTime(2011, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -70,
                            DateOfBirth = new DateTime(1952, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2001, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -71,
                            DateOfBirth = new DateTime(1959, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            HireDate = new DateTime(2013, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bailey",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -72,
                            DateOfBirth = new DateTime(1959, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jordan",
                            HireDate = new DateTime(2007, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Stewart",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -73,
                            DateOfBirth = new DateTime(1950, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ashley",
                            HireDate = new DateTime(2005, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roberts",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -74,
                            DateOfBirth = new DateTime(1964, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ann",
                            HireDate = new DateTime(2002, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peterson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -75,
                            DateOfBirth = new DateTime(1952, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Heather",
                            HireDate = new DateTime(2008, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bennet",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -76,
                            DateOfBirth = new DateTime(1972, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Albert",
                            HireDate = new DateTime(2005, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Perez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -77,
                            DateOfBirth = new DateTime(1971, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Madison",
                            HireDate = new DateTime(2002, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rodriguez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -78,
                            DateOfBirth = new DateTime(1972, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Randy",
                            HireDate = new DateTime(2014, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richardson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -79,
                            DateOfBirth = new DateTime(1978, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalie",
                            HireDate = new DateTime(2010, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ruiz",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -80,
                            DateOfBirth = new DateTime(1973, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Megan",
                            HireDate = new DateTime(2009, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -81,
                            DateOfBirth = new DateTime(1974, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dorothy",
                            HireDate = new DateTime(2007, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ramirez",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -82,
                            DateOfBirth = new DateTime(1965, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Richard",
                            HireDate = new DateTime(2003, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roberts",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -83,
                            DateOfBirth = new DateTime(1952, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nicholas",
                            HireDate = new DateTime(2003, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Robinson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -84,
                            DateOfBirth = new DateTime(1971, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Albert",
                            HireDate = new DateTime(2010, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mendoza",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -85,
                            DateOfBirth = new DateTime(1951, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Albert",
                            HireDate = new DateTime(2004, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Diaz",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -86,
                            DateOfBirth = new DateTime(1978, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Edward",
                            HireDate = new DateTime(2004, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hernandez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -87,
                            DateOfBirth = new DateTime(1973, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HireDate = new DateTime(2002, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brooks",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -88,
                            DateOfBirth = new DateTime(1969, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            HireDate = new DateTime(2014, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hall",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -89,
                            DateOfBirth = new DateTime(1959, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Philip",
                            HireDate = new DateTime(2000, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Phillips",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -90,
                            DateOfBirth = new DateTime(1968, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ralph",
                            HireDate = new DateTime(2000, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Price",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -91,
                            DateOfBirth = new DateTime(1958, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brenda",
                            HireDate = new DateTime(2008, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -92,
                            DateOfBirth = new DateTime(1978, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janet",
                            HireDate = new DateTime(2001, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -93,
                            DateOfBirth = new DateTime(1980, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Laura",
                            HireDate = new DateTime(2001, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Evans",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -94,
                            DateOfBirth = new DateTime(1957, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2006, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Miller",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -95,
                            DateOfBirth = new DateTime(1962, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sandra",
                            HireDate = new DateTime(2004, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bailey",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -96,
                            DateOfBirth = new DateTime(1954, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            HireDate = new DateTime(2011, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanchez",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -97,
                            DateOfBirth = new DateTime(1970, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paul",
                            HireDate = new DateTime(2013, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cox",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -98,
                            DateOfBirth = new DateTime(1977, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ronald",
                            HireDate = new DateTime(2004, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Watson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -99,
                            DateOfBirth = new DateTime(1980, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cynthia",
                            HireDate = new DateTime(2006, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thompson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -100,
                            DateOfBirth = new DateTime(1959, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amber",
                            HireDate = new DateTime(2006, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Flores",
                            LocationID = -4
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("postalcode")
                        .HasColumnType("char(6)")
                        .HasMaxLength(6)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Address = "123 Main Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T6M5W2"
                        },
                        new
                        {
                            ID = -2,
                            Address = "567 Side Street",
                            City = "Vancouver",
                            Name = "",
                            PostalCode = "T8M2X2"
                        },
                        new
                        {
                            ID = -3,
                            Address = "246 Boulevard Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T2Y8Z2"
                        },
                        new
                        {
                            ID = -4,
                            Address = "357 Back Street",
                            City = "Calgary",
                            Name = "",
                            PostalCode = "T9T7L2"
                        },
                        new
                        {
                            ID = -5,
                            Address = "852 Sesame Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T9M2A9"
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Employee", b =>
                {
                    b.HasOne("_4Point1_EF.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .HasConstraintName("FK_Employee_Location")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
