// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4Point1_EF.Models;

namespace _4Point1_EF.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200918173851_Restrict")]
    partial class Restrict
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_4Point1_EF.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("dateofbirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("enddate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<DateTime>("HireDate")
                        .HasColumnName("hiredate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("LocationID")
                        .HasColumnName("location_id")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("LocationID")
                        .HasName("FK_Employee_Location");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DateOfBirth = new DateTime(1974, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Theresa",
                            HireDate = new DateTime(2001, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dylan",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -2,
                            DateOfBirth = new DateTime(1952, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Timothy",
                            HireDate = new DateTime(2000, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Benjamin",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -3,
                            DateOfBirth = new DateTime(1956, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jordan",
                            HireDate = new DateTime(2000, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gregory",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -4,
                            DateOfBirth = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sean",
                            HireDate = new DateTime(2013, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Michael",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -5,
                            DateOfBirth = new DateTime(1958, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brian",
                            HireDate = new DateTime(2010, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patrick",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -6,
                            DateOfBirth = new DateTime(1970, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jerry",
                            HireDate = new DateTime(2009, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sean",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -7,
                            DateOfBirth = new DateTime(1971, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rose",
                            HireDate = new DateTime(2014, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kevin",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -8,
                            DateOfBirth = new DateTime(1953, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeremy",
                            HireDate = new DateTime(2007, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jack",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -9,
                            DateOfBirth = new DateTime(1958, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kevin",
                            HireDate = new DateTime(2009, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Philip",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -10,
                            DateOfBirth = new DateTime(1956, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            HireDate = new DateTime(2013, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gabriel",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -11,
                            DateOfBirth = new DateTime(1973, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bobby",
                            HireDate = new DateTime(2011, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Samuel",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -12,
                            DateOfBirth = new DateTime(1953, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Judith",
                            HireDate = new DateTime(2000, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zachary",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -13,
                            DateOfBirth = new DateTime(1964, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Debra",
                            HireDate = new DateTime(2008, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jason",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -14,
                            DateOfBirth = new DateTime(1971, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rebecca",
                            HireDate = new DateTime(2002, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Joshua",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -15,
                            DateOfBirth = new DateTime(1963, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thomas",
                            HireDate = new DateTime(2002, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Paul",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -16,
                            DateOfBirth = new DateTime(1951, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eugene",
                            HireDate = new DateTime(2001, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Michael",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -17,
                            DateOfBirth = new DateTime(1962, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruce",
                            HireDate = new DateTime(2014, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patrick",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -18,
                            DateOfBirth = new DateTime(1967, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Keith",
                            HireDate = new DateTime(2010, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Eugene",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -19,
                            DateOfBirth = new DateTime(1964, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrea",
                            HireDate = new DateTime(2002, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Joseph",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -20,
                            DateOfBirth = new DateTime(1974, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Margaret",
                            HireDate = new DateTime(2004, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peter",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -21,
                            DateOfBirth = new DateTime(1954, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Keith",
                            HireDate = new DateTime(2008, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Louis",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -22,
                            DateOfBirth = new DateTime(1979, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lauren",
                            HireDate = new DateTime(2005, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Michael",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -23,
                            DateOfBirth = new DateTime(1973, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kayla",
                            HireDate = new DateTime(2012, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nicholas",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -24,
                            DateOfBirth = new DateTime(1977, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Douglas",
                            HireDate = new DateTime(2010, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Vincent",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -25,
                            DateOfBirth = new DateTime(1966, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janice",
                            HireDate = new DateTime(2008, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mark",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -26,
                            DateOfBirth = new DateTime(1979, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bryan",
                            HireDate = new DateTime(2004, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mark",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -27,
                            DateOfBirth = new DateTime(1951, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Donna",
                            HireDate = new DateTime(2012, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roger",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -28,
                            DateOfBirth = new DateTime(1975, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linda",
                            HireDate = new DateTime(2004, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Christian",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -29,
                            DateOfBirth = new DateTime(1962, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jose",
                            HireDate = new DateTime(2011, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Frank",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -30,
                            DateOfBirth = new DateTime(1966, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeremy",
                            HireDate = new DateTime(2014, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Keith",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -31,
                            DateOfBirth = new DateTime(1953, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            HireDate = new DateTime(2010, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gabriel",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -32,
                            DateOfBirth = new DateTime(1964, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Debra",
                            HireDate = new DateTime(2002, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jeffrey",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -33,
                            DateOfBirth = new DateTime(1976, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            HireDate = new DateTime(2013, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richard",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -34,
                            DateOfBirth = new DateTime(1963, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pamela",
                            HireDate = new DateTime(2005, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "George",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -35,
                            DateOfBirth = new DateTime(1950, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eric",
                            HireDate = new DateTime(2012, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carl",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -36,
                            DateOfBirth = new DateTime(1955, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kathleen",
                            HireDate = new DateTime(2006, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ralph",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -37,
                            DateOfBirth = new DateTime(1969, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Matthew",
                            HireDate = new DateTime(2002, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peter",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -38,
                            DateOfBirth = new DateTime(1965, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janet",
                            HireDate = new DateTime(2013, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Andrew",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -39,
                            DateOfBirth = new DateTime(1962, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jason",
                            HireDate = new DateTime(2011, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gregory",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -40,
                            DateOfBirth = new DateTime(1968, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jerry",
                            HireDate = new DateTime(2008, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edward",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -41,
                            DateOfBirth = new DateTime(1960, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Debra",
                            HireDate = new DateTime(2007, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wayne",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -42,
                            DateOfBirth = new DateTime(1965, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruce",
                            HireDate = new DateTime(2009, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patrick",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -43,
                            DateOfBirth = new DateTime(1952, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ronald",
                            HireDate = new DateTime(2007, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roy",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -44,
                            DateOfBirth = new DateTime(1959, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2003, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Alexander",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -45,
                            DateOfBirth = new DateTime(1963, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bryan",
                            HireDate = new DateTime(2011, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brian",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -46,
                            DateOfBirth = new DateTime(1959, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Albert",
                            HireDate = new DateTime(2012, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dennis",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -47,
                            DateOfBirth = new DateTime(1969, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julia",
                            HireDate = new DateTime(2014, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jesse",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -48,
                            DateOfBirth = new DateTime(1970, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Barbara",
                            HireDate = new DateTime(2013, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Arthur",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -49,
                            DateOfBirth = new DateTime(1979, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Diane",
                            HireDate = new DateTime(2005, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mark",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -50,
                            DateOfBirth = new DateTime(1966, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ralph",
                            HireDate = new DateTime(2009, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roger",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -51,
                            DateOfBirth = new DateTime(1953, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carol",
                            HireDate = new DateTime(2010, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Larry",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -52,
                            DateOfBirth = new DateTime(1967, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sean",
                            HireDate = new DateTime(2011, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Albert",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -53,
                            DateOfBirth = new DateTime(1976, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Justin",
                            HireDate = new DateTime(2011, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Frank",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -54,
                            DateOfBirth = new DateTime(1962, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2011, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kyle",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -55,
                            DateOfBirth = new DateTime(1954, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joshua",
                            HireDate = new DateTime(2009, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jordan",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -56,
                            DateOfBirth = new DateTime(1962, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Keith",
                            HireDate = new DateTime(2004, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Russell",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -57,
                            DateOfBirth = new DateTime(1971, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ashley",
                            HireDate = new DateTime(2012, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Arthur",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -58,
                            DateOfBirth = new DateTime(1955, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arthur",
                            HireDate = new DateTime(2011, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Noah",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -59,
                            DateOfBirth = new DateTime(1957, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ruth",
                            HireDate = new DateTime(2004, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ethan",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -60,
                            DateOfBirth = new DateTime(1961, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brian",
                            HireDate = new DateTime(2002, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Alexander",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -61,
                            DateOfBirth = new DateTime(1955, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jason",
                            HireDate = new DateTime(2008, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Philip",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -62,
                            DateOfBirth = new DateTime(1967, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Melissa",
                            HireDate = new DateTime(2011, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bradley",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -63,
                            DateOfBirth = new DateTime(1974, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Logan",
                            HireDate = new DateTime(2003, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Austin",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -64,
                            DateOfBirth = new DateTime(1958, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Douglas",
                            HireDate = new DateTime(2000, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Christopher",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -65,
                            DateOfBirth = new DateTime(1953, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anthony",
                            HireDate = new DateTime(2007, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Austin",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -66,
                            DateOfBirth = new DateTime(1962, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Austin",
                            HireDate = new DateTime(2008, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Randy",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -67,
                            DateOfBirth = new DateTime(1950, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kelly",
                            HireDate = new DateTime(2004, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kenneth",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -68,
                            DateOfBirth = new DateTime(1962, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Harold",
                            HireDate = new DateTime(2009, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Christopher",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -69,
                            DateOfBirth = new DateTime(1961, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samuel",
                            HireDate = new DateTime(2008, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Noah",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -70,
                            DateOfBirth = new DateTime(1976, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jack",
                            HireDate = new DateTime(2009, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnny",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -71,
                            DateOfBirth = new DateTime(1958, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linda",
                            HireDate = new DateTime(2006, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -72,
                            DateOfBirth = new DateTime(1980, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jessica",
                            HireDate = new DateTime(2002, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Samuel",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -73,
                            DateOfBirth = new DateTime(1967, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kenneth",
                            HireDate = new DateTime(2014, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Steven",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -74,
                            DateOfBirth = new DateTime(1970, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Denise",
                            HireDate = new DateTime(2001, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnny",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -75,
                            DateOfBirth = new DateTime(1953, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Willie",
                            HireDate = new DateTime(2012, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Raymond",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -76,
                            DateOfBirth = new DateTime(1979, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nicole",
                            HireDate = new DateTime(2005, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bobby",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -77,
                            DateOfBirth = new DateTime(1978, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deborah",
                            HireDate = new DateTime(2008, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Paul",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -78,
                            DateOfBirth = new DateTime(1962, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samantha",
                            HireDate = new DateTime(2009, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richard",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -79,
                            DateOfBirth = new DateTime(1952, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brittany",
                            HireDate = new DateTime(2014, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bobby",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -80,
                            DateOfBirth = new DateTime(1966, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Donna",
                            HireDate = new DateTime(2003, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Juan",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -81,
                            DateOfBirth = new DateTime(1966, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anthony",
                            HireDate = new DateTime(2009, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Christian",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -82,
                            DateOfBirth = new DateTime(1977, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Henry",
                            HireDate = new DateTime(2009, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brian",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -83,
                            DateOfBirth = new DateTime(1975, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexis",
                            HireDate = new DateTime(2008, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Charles",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -84,
                            DateOfBirth = new DateTime(1959, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Logan",
                            HireDate = new DateTime(2010, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ralph",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -85,
                            DateOfBirth = new DateTime(1956, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kayla",
                            HireDate = new DateTime(2003, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nathan",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -86,
                            DateOfBirth = new DateTime(1952, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            HireDate = new DateTime(2013, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Douglas",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -87,
                            DateOfBirth = new DateTime(1971, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Donna",
                            HireDate = new DateTime(2002, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tyler",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -88,
                            DateOfBirth = new DateTime(1978, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Billy",
                            HireDate = new DateTime(2014, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Samuel",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -89,
                            DateOfBirth = new DateTime(1965, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Melissa",
                            HireDate = new DateTime(2013, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peter",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -90,
                            DateOfBirth = new DateTime(1950, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Abigail",
                            HireDate = new DateTime(2007, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Frank",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -91,
                            DateOfBirth = new DateTime(1975, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Harold",
                            HireDate = new DateTime(2008, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jesse",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -92,
                            DateOfBirth = new DateTime(1950, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruce",
                            HireDate = new DateTime(2000, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Adam",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -93,
                            DateOfBirth = new DateTime(1977, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jesse",
                            HireDate = new DateTime(2014, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mark",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -94,
                            DateOfBirth = new DateTime(1952, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joshua",
                            HireDate = new DateTime(2012, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Henry",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -95,
                            DateOfBirth = new DateTime(1953, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Aaron",
                            HireDate = new DateTime(2005, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Alexander",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -96,
                            DateOfBirth = new DateTime(1979, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bradley",
                            HireDate = new DateTime(2002, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nicholas",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -97,
                            DateOfBirth = new DateTime(1962, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Frank",
                            HireDate = new DateTime(2013, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richard",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -98,
                            DateOfBirth = new DateTime(1955, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jose",
                            HireDate = new DateTime(2013, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tyler",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -99,
                            DateOfBirth = new DateTime(1959, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nancy",
                            HireDate = new DateTime(2011, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sean",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -100,
                            DateOfBirth = new DateTime(1956, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dorothy",
                            HireDate = new DateTime(2002, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jack",
                            LocationID = -1
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("postalcode")
                        .HasColumnType("char(6)")
                        .HasMaxLength(6)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Address = "123 Main Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T6M5W2"
                        },
                        new
                        {
                            ID = -2,
                            Address = "567 Side Street",
                            City = "Vancouver",
                            Name = "",
                            PostalCode = "T8M2X2"
                        },
                        new
                        {
                            ID = -3,
                            Address = "246 Boulevard Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T2Y8Z2"
                        },
                        new
                        {
                            ID = -4,
                            Address = "357 Back Street",
                            City = "Calgary",
                            Name = "",
                            PostalCode = "T9T7L2"
                        },
                        new
                        {
                            ID = -5,
                            Address = "852 Sesame Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T9M2A9"
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Employee", b =>
                {
                    b.HasOne("_4Point1_EF.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .HasConstraintName("FK_Employee_Location")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
