// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4Point1_EF.Models;

namespace _4Point1_EF.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200918173532_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_4Point1_EF.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("dateofbirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("enddate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<DateTime>("HireDate")
                        .HasColumnName("hiredate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("LocationID")
                        .HasColumnName("location_id")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("LocationID")
                        .HasName("FK_Employee_Location");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DateOfBirth = new DateTime(1961, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deborah",
                            HireDate = new DateTime(2007, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Michael",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -2,
                            DateOfBirth = new DateTime(1980, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Doris",
                            HireDate = new DateTime(2003, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edward",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -3,
                            DateOfBirth = new DateTime(1965, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samantha",
                            HireDate = new DateTime(2000, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nathan",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -4,
                            DateOfBirth = new DateTime(1973, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rose",
                            HireDate = new DateTime(2011, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jeffrey",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -5,
                            DateOfBirth = new DateTime(1958, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janice",
                            HireDate = new DateTime(2011, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -6,
                            DateOfBirth = new DateTime(1951, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Aaron",
                            HireDate = new DateTime(2000, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Larry",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -7,
                            DateOfBirth = new DateTime(1968, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Helen",
                            HireDate = new DateTime(2012, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jack",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -8,
                            DateOfBirth = new DateTime(1959, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charlotte",
                            HireDate = new DateTime(2005, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sean",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -9,
                            DateOfBirth = new DateTime(1951, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Karen",
                            HireDate = new DateTime(2010, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Andrew",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -10,
                            DateOfBirth = new DateTime(1968, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vincent",
                            HireDate = new DateTime(2010, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Logan",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -11,
                            DateOfBirth = new DateTime(1968, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beverly",
                            HireDate = new DateTime(2008, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Daniel",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -12,
                            DateOfBirth = new DateTime(1978, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amy",
                            HireDate = new DateTime(2007, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Henry",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -13,
                            DateOfBirth = new DateTime(1951, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beverly",
                            HireDate = new DateTime(2001, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Stephen",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -14,
                            DateOfBirth = new DateTime(1978, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            HireDate = new DateTime(2006, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Christopher",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -15,
                            DateOfBirth = new DateTime(1978, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Johnny",
                            HireDate = new DateTime(2001, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Alexander",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -16,
                            DateOfBirth = new DateTime(1967, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kathryn",
                            HireDate = new DateTime(2006, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bryan",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -17,
                            DateOfBirth = new DateTime(1967, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Susan",
                            HireDate = new DateTime(2009, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Arthur",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -18,
                            DateOfBirth = new DateTime(1974, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HireDate = new DateTime(2003, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Douglas",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -19,
                            DateOfBirth = new DateTime(1966, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cheryl",
                            HireDate = new DateTime(2009, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "David",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -20,
                            DateOfBirth = new DateTime(1960, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julia",
                            HireDate = new DateTime(2002, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nicholas",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -21,
                            DateOfBirth = new DateTime(1965, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            HireDate = new DateTime(2001, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edward",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -22,
                            DateOfBirth = new DateTime(1967, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrew",
                            HireDate = new DateTime(2013, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jordan",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -23,
                            DateOfBirth = new DateTime(1972, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lauren",
                            HireDate = new DateTime(2009, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jacob",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -24,
                            DateOfBirth = new DateTime(1967, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Janet",
                            HireDate = new DateTime(2010, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Adam",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -25,
                            DateOfBirth = new DateTime(1955, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Noah",
                            HireDate = new DateTime(2002, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brian",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -26,
                            DateOfBirth = new DateTime(1957, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deborah",
                            HireDate = new DateTime(2006, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brian",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -27,
                            DateOfBirth = new DateTime(1978, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Steven",
                            HireDate = new DateTime(2008, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mark",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -28,
                            DateOfBirth = new DateTime(1951, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2008, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bradley",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -29,
                            DateOfBirth = new DateTime(1966, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kayla",
                            HireDate = new DateTime(2002, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bradley",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -30,
                            DateOfBirth = new DateTime(1956, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samuel",
                            HireDate = new DateTime(2014, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tyler",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -31,
                            DateOfBirth = new DateTime(1969, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Judith",
                            HireDate = new DateTime(2013, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gabriel",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -32,
                            DateOfBirth = new DateTime(1969, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thomas",
                            HireDate = new DateTime(2001, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Albert",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -33,
                            DateOfBirth = new DateTime(1978, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Madison",
                            HireDate = new DateTime(2009, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ralph",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -34,
                            DateOfBirth = new DateTime(1954, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jean",
                            HireDate = new DateTime(2002, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Larry",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -35,
                            DateOfBirth = new DateTime(1960, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            HireDate = new DateTime(2006, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Steven",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -36,
                            DateOfBirth = new DateTime(1978, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nicole",
                            HireDate = new DateTime(2013, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jack",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -37,
                            DateOfBirth = new DateTime(1957, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stephanie",
                            HireDate = new DateTime(2010, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Juan",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -38,
                            DateOfBirth = new DateTime(1972, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joyce",
                            HireDate = new DateTime(2009, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Aaron",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -39,
                            DateOfBirth = new DateTime(1962, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jason",
                            HireDate = new DateTime(2003, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jason",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -40,
                            DateOfBirth = new DateTime(1959, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marilyn",
                            HireDate = new DateTime(2002, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zachary",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -41,
                            DateOfBirth = new DateTime(1975, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eugene",
                            HireDate = new DateTime(2002, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mark",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -42,
                            DateOfBirth = new DateTime(1964, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beverly",
                            HireDate = new DateTime(2013, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Charles",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -43,
                            DateOfBirth = new DateTime(1953, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beverly",
                            HireDate = new DateTime(2014, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edward",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -44,
                            DateOfBirth = new DateTime(1979, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethan",
                            HireDate = new DateTime(2004, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -45,
                            DateOfBirth = new DateTime(1953, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethan",
                            HireDate = new DateTime(2012, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Daniel",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -46,
                            DateOfBirth = new DateTime(1979, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samantha",
                            HireDate = new DateTime(2003, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harold",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -47,
                            DateOfBirth = new DateTime(1956, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rachel",
                            HireDate = new DateTime(2008, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -48,
                            DateOfBirth = new DateTime(1975, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kimberly",
                            HireDate = new DateTime(2001, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Eugene",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -49,
                            DateOfBirth = new DateTime(1971, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Megan",
                            HireDate = new DateTime(2010, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Eugene",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -50,
                            DateOfBirth = new DateTime(1972, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marie",
                            HireDate = new DateTime(2002, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Michael",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -51,
                            DateOfBirth = new DateTime(1951, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amy",
                            HireDate = new DateTime(2013, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Stephen",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -52,
                            DateOfBirth = new DateTime(1954, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            HireDate = new DateTime(2010, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Charles",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -53,
                            DateOfBirth = new DateTime(1953, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            HireDate = new DateTime(2003, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wayne",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -54,
                            DateOfBirth = new DateTime(1970, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Danielle",
                            HireDate = new DateTime(2014, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sean",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -55,
                            DateOfBirth = new DateTime(1968, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2007, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Donald",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -56,
                            DateOfBirth = new DateTime(1978, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalie",
                            HireDate = new DateTime(2011, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nathan",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -57,
                            DateOfBirth = new DateTime(1966, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            HireDate = new DateTime(2004, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Andrew",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -58,
                            DateOfBirth = new DateTime(1956, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christian",
                            HireDate = new DateTime(2011, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brian",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -59,
                            DateOfBirth = new DateTime(1968, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            HireDate = new DateTime(2011, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "William",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -60,
                            DateOfBirth = new DateTime(1962, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kimberly",
                            HireDate = new DateTime(2004, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zachary",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -61,
                            DateOfBirth = new DateTime(1962, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Terry",
                            HireDate = new DateTime(2010, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "David",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -62,
                            DateOfBirth = new DateTime(1964, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Donna",
                            HireDate = new DateTime(2001, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Randy",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -63,
                            DateOfBirth = new DateTime(1958, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jason",
                            HireDate = new DateTime(2006, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ethan",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -64,
                            DateOfBirth = new DateTime(1975, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jason",
                            HireDate = new DateTime(2002, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Juan",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -65,
                            DateOfBirth = new DateTime(1969, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            HireDate = new DateTime(2007, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Joseph",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -66,
                            DateOfBirth = new DateTime(1964, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalie",
                            HireDate = new DateTime(2010, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Donald",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -67,
                            DateOfBirth = new DateTime(1974, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexis",
                            HireDate = new DateTime(2010, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anthony",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -68,
                            DateOfBirth = new DateTime(1961, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            HireDate = new DateTime(2000, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Daniel",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -69,
                            DateOfBirth = new DateTime(1980, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2005, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Donald",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -70,
                            DateOfBirth = new DateTime(1970, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hannah",
                            HireDate = new DateTime(2012, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Noah",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -71,
                            DateOfBirth = new DateTime(1976, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Patrick",
                            HireDate = new DateTime(2014, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ralph",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -72,
                            DateOfBirth = new DateTime(1950, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lauren",
                            HireDate = new DateTime(2010, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Philip",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -73,
                            DateOfBirth = new DateTime(1955, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ralph",
                            HireDate = new DateTime(2011, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Adam",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -74,
                            DateOfBirth = new DateTime(1956, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Austin",
                            HireDate = new DateTime(2013, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tyler",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -75,
                            DateOfBirth = new DateTime(1977, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cynthia",
                            HireDate = new DateTime(2004, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Russell",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -76,
                            DateOfBirth = new DateTime(1971, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ryan",
                            HireDate = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Charles",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -77,
                            DateOfBirth = new DateTime(1959, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Harold",
                            HireDate = new DateTime(2007, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Larry",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -78,
                            DateOfBirth = new DateTime(1964, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Peter",
                            HireDate = new DateTime(2006, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Benjamin",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -79,
                            DateOfBirth = new DateTime(1969, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jason",
                            HireDate = new DateTime(2005, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Juan",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -80,
                            DateOfBirth = new DateTime(1950, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nathan",
                            HireDate = new DateTime(2004, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jonathan",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -81,
                            DateOfBirth = new DateTime(1961, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eric",
                            HireDate = new DateTime(2011, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roger",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -82,
                            DateOfBirth = new DateTime(1971, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sandra",
                            HireDate = new DateTime(2006, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Matthew",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -83,
                            DateOfBirth = new DateTime(1968, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Barbara",
                            HireDate = new DateTime(2014, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Louis",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -84,
                            DateOfBirth = new DateTime(1976, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kelly",
                            HireDate = new DateTime(2007, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Henry",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -85,
                            DateOfBirth = new DateTime(1954, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Julie",
                            HireDate = new DateTime(2001, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Samuel",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -86,
                            DateOfBirth = new DateTime(1956, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rose",
                            HireDate = new DateTime(2004, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brandon",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -87,
                            DateOfBirth = new DateTime(1951, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amber",
                            HireDate = new DateTime(2014, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Timothy",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -88,
                            DateOfBirth = new DateTime(1977, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christian",
                            HireDate = new DateTime(2003, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dennis",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -89,
                            DateOfBirth = new DateTime(1967, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Madison",
                            HireDate = new DateTime(2001, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Austin",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -90,
                            DateOfBirth = new DateTime(1952, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Matthew",
                            HireDate = new DateTime(2007, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Louis",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -91,
                            DateOfBirth = new DateTime(1965, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tyler",
                            HireDate = new DateTime(2003, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Daniel",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -92,
                            DateOfBirth = new DateTime(1956, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2005, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Charles",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -93,
                            DateOfBirth = new DateTime(1978, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Willie",
                            HireDate = new DateTime(2008, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Timothy",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -94,
                            DateOfBirth = new DateTime(1979, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Scott",
                            HireDate = new DateTime(2013, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nicholas",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -95,
                            DateOfBirth = new DateTime(1966, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Frank",
                            HireDate = new DateTime(2006, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ryan",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -96,
                            DateOfBirth = new DateTime(1961, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jordan",
                            HireDate = new DateTime(2003, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "James",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -97,
                            DateOfBirth = new DateTime(1953, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Peter",
                            HireDate = new DateTime(2005, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Randy",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -98,
                            DateOfBirth = new DateTime(1953, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rose",
                            HireDate = new DateTime(2007, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Steven",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -99,
                            DateOfBirth = new DateTime(1960, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalie",
                            HireDate = new DateTime(2004, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brian",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -100,
                            DateOfBirth = new DateTime(1975, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stephen",
                            HireDate = new DateTime(2008, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Albert",
                            LocationID = -3
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("postalcode")
                        .HasColumnType("char(6)")
                        .HasMaxLength(6)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Address = "123 Main Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T6M5W2"
                        },
                        new
                        {
                            ID = -2,
                            Address = "567 Side Street",
                            City = "Vancouver",
                            Name = "",
                            PostalCode = "T8M2X2"
                        },
                        new
                        {
                            ID = -3,
                            Address = "246 Boulevard Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T2Y8Z2"
                        },
                        new
                        {
                            ID = -4,
                            Address = "357 Back Street",
                            City = "Calgary",
                            Name = "",
                            PostalCode = "T9T7L2"
                        },
                        new
                        {
                            ID = -5,
                            Address = "852 Sesame Street",
                            City = "Edmonton",
                            Name = "",
                            PostalCode = "T9M2A9"
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Employee", b =>
                {
                    b.HasOne("_4Point1_EF.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .HasConstraintName("FK_Employee_Location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
