// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4Point1_EF.Models;

namespace _4Point1_EF.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20200918175802_LocationNames")]
    partial class LocationNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_4Point1_EF.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("dateofbirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("enddate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<DateTime>("HireDate")
                        .HasColumnName("hiredate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("LocationID")
                        .HasColumnName("location_id")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("LocationID")
                        .HasName("FK_Employee_Location");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DateOfBirth = new DateTime(1969, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pamela",
                            HireDate = new DateTime(2000, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Edwards",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -2,
                            DateOfBirth = new DateTime(1960, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brittany",
                            HireDate = new DateTime(2002, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -3,
                            DateOfBirth = new DateTime(1973, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jacqueline",
                            HireDate = new DateTime(2006, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Allen",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -4,
                            DateOfBirth = new DateTime(1977, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethan",
                            HireDate = new DateTime(2014, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -5,
                            DateOfBirth = new DateTime(1956, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joshua",
                            HireDate = new DateTime(2005, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hill",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -6,
                            DateOfBirth = new DateTime(1963, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beverly",
                            HireDate = new DateTime(2006, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cox",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -7,
                            DateOfBirth = new DateTime(1979, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Isabella",
                            HireDate = new DateTime(2011, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Campbell",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -8,
                            DateOfBirth = new DateTime(1964, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Theresa",
                            HireDate = new DateTime(2008, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nelson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -9,
                            DateOfBirth = new DateTime(1966, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Timothy",
                            HireDate = new DateTime(2014, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -10,
                            DateOfBirth = new DateTime(1969, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Patrick",
                            HireDate = new DateTime(2001, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Allen",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -11,
                            DateOfBirth = new DateTime(1958, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Beverly",
                            HireDate = new DateTime(2009, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jones",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -12,
                            DateOfBirth = new DateTime(1956, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carol",
                            HireDate = new DateTime(2005, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "King",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -13,
                            DateOfBirth = new DateTime(1967, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brian",
                            HireDate = new DateTime(2009, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -14,
                            DateOfBirth = new DateTime(1965, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jerry",
                            HireDate = new DateTime(2001, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Campbell",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -15,
                            DateOfBirth = new DateTime(1967, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Shirley",
                            HireDate = new DateTime(2013, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hernandez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -16,
                            DateOfBirth = new DateTime(1973, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sharon",
                            HireDate = new DateTime(2010, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Allen",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -17,
                            DateOfBirth = new DateTime(1970, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hannah",
                            HireDate = new DateTime(2002, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lewis",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -18,
                            DateOfBirth = new DateTime(1974, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeremy",
                            HireDate = new DateTime(2000, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jackson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -19,
                            DateOfBirth = new DateTime(1961, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bobby",
                            HireDate = new DateTime(2013, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wright",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -20,
                            DateOfBirth = new DateTime(1961, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carol",
                            HireDate = new DateTime(2005, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -21,
                            DateOfBirth = new DateTime(1968, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christopher",
                            HireDate = new DateTime(2006, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -22,
                            DateOfBirth = new DateTime(1965, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            HireDate = new DateTime(2009, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hill",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -23,
                            DateOfBirth = new DateTime(1954, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Scott",
                            HireDate = new DateTime(2004, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopez",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -24,
                            DateOfBirth = new DateTime(1976, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Heather",
                            HireDate = new DateTime(2009, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Campbell",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -25,
                            DateOfBirth = new DateTime(1980, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Theresa",
                            HireDate = new DateTime(2006, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brooks",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -26,
                            DateOfBirth = new DateTime(1974, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Madison",
                            HireDate = new DateTime(2001, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hill",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -27,
                            DateOfBirth = new DateTime(1956, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Philip",
                            HireDate = new DateTime(2006, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -28,
                            DateOfBirth = new DateTime(1965, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joan",
                            HireDate = new DateTime(2000, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -29,
                            DateOfBirth = new DateTime(1951, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ronald",
                            HireDate = new DateTime(2005, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Baker",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -30,
                            DateOfBirth = new DateTime(1963, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Frances",
                            HireDate = new DateTime(2012, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "James",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -31,
                            DateOfBirth = new DateTime(1961, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samuel",
                            HireDate = new DateTime(2014, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -32,
                            DateOfBirth = new DateTime(1951, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rachel",
                            HireDate = new DateTime(2008, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanchez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -33,
                            DateOfBirth = new DateTime(1979, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2003, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jimenez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -34,
                            DateOfBirth = new DateTime(1957, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anthony",
                            HireDate = new DateTime(2012, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Richardson",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -35,
                            DateOfBirth = new DateTime(1951, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jean",
                            HireDate = new DateTime(2004, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cooper",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -36,
                            DateOfBirth = new DateTime(1957, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michelle",
                            HireDate = new DateTime(2010, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -37,
                            DateOfBirth = new DateTime(1974, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexis",
                            HireDate = new DateTime(2003, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -38,
                            DateOfBirth = new DateTime(1957, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kevin",
                            HireDate = new DateTime(2012, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nelson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -39,
                            DateOfBirth = new DateTime(1968, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pamela",
                            HireDate = new DateTime(2000, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -40,
                            DateOfBirth = new DateTime(1976, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jessica",
                            HireDate = new DateTime(2009, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Evans",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -41,
                            DateOfBirth = new DateTime(1955, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Aaron",
                            HireDate = new DateTime(2008, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -42,
                            DateOfBirth = new DateTime(1962, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kenneth",
                            HireDate = new DateTime(2014, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanders",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -43,
                            DateOfBirth = new DateTime(1979, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Philip",
                            HireDate = new DateTime(2005, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cooper",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -44,
                            DateOfBirth = new DateTime(1966, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carolyn",
                            HireDate = new DateTime(2011, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -45,
                            DateOfBirth = new DateTime(1968, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tyler",
                            HireDate = new DateTime(2012, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "James",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -46,
                            DateOfBirth = new DateTime(1965, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Scott",
                            HireDate = new DateTime(2008, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ramos",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -47,
                            DateOfBirth = new DateTime(1958, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            HireDate = new DateTime(2011, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Turner",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -48,
                            DateOfBirth = new DateTime(1977, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linda",
                            HireDate = new DateTime(2009, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peterson",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -49,
                            DateOfBirth = new DateTime(1954, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Betty",
                            HireDate = new DateTime(2014, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Peterson",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -50,
                            DateOfBirth = new DateTime(1972, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            HireDate = new DateTime(2007, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Perez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -51,
                            DateOfBirth = new DateTime(1965, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Doris",
                            HireDate = new DateTime(2011, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -52,
                            DateOfBirth = new DateTime(1959, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cynthia",
                            HireDate = new DateTime(2004, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Stewart",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -53,
                            DateOfBirth = new DateTime(1978, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nathan",
                            HireDate = new DateTime(2004, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Foster",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -54,
                            DateOfBirth = new DateTime(1974, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            HireDate = new DateTime(2000, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanchez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -55,
                            DateOfBirth = new DateTime(1964, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            HireDate = new DateTime(2005, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Foster",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -56,
                            DateOfBirth = new DateTime(1977, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victoria",
                            HireDate = new DateTime(2000, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Price",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -57,
                            DateOfBirth = new DateTime(1974, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deborah",
                            HireDate = new DateTime(2001, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Alvarez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -58,
                            DateOfBirth = new DateTime(1952, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            HireDate = new DateTime(2000, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -59,
                            DateOfBirth = new DateTime(1975, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arthur",
                            HireDate = new DateTime(2008, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nelson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -60,
                            DateOfBirth = new DateTime(1952, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Justin",
                            HireDate = new DateTime(2003, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Torres",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -61,
                            DateOfBirth = new DateTime(1956, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carl",
                            HireDate = new DateTime(2010, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -62,
                            DateOfBirth = new DateTime(1950, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brandon",
                            HireDate = new DateTime(2005, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cox",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -63,
                            DateOfBirth = new DateTime(1975, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Keith",
                            HireDate = new DateTime(2006, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wood",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -64,
                            DateOfBirth = new DateTime(1961, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joshua",
                            HireDate = new DateTime(2002, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roberts",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -65,
                            DateOfBirth = new DateTime(1963, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            HireDate = new DateTime(2010, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hughes",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -66,
                            DateOfBirth = new DateTime(1966, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            HireDate = new DateTime(2011, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hughes",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -67,
                            DateOfBirth = new DateTime(1951, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ronald",
                            HireDate = new DateTime(2005, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -68,
                            DateOfBirth = new DateTime(1950, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dylan",
                            HireDate = new DateTime(2010, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanders",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -69,
                            DateOfBirth = new DateTime(1958, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HireDate = new DateTime(2013, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cooper",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -70,
                            DateOfBirth = new DateTime(1972, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexander",
                            HireDate = new DateTime(2006, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Stewart",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -71,
                            DateOfBirth = new DateTime(1966, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Randy",
                            HireDate = new DateTime(2003, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -72,
                            DateOfBirth = new DateTime(1963, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paul",
                            HireDate = new DateTime(2008, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gutierrez",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -73,
                            DateOfBirth = new DateTime(1958, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Susan",
                            HireDate = new DateTime(2014, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -74,
                            DateOfBirth = new DateTime(1972, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            HireDate = new DateTime(2009, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chavez",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -75,
                            DateOfBirth = new DateTime(1967, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Matthew",
                            HireDate = new DateTime(2013, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ruiz",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -76,
                            DateOfBirth = new DateTime(1962, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joyce",
                            HireDate = new DateTime(2013, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -77,
                            DateOfBirth = new DateTime(1957, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Willie",
                            HireDate = new DateTime(2001, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ortiz",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -78,
                            DateOfBirth = new DateTime(1959, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeremy",
                            HireDate = new DateTime(2001, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wood",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -79,
                            DateOfBirth = new DateTime(1960, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruce",
                            HireDate = new DateTime(2013, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Flores",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -80,
                            DateOfBirth = new DateTime(1967, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nathan",
                            HireDate = new DateTime(2005, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Baker",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -81,
                            DateOfBirth = new DateTime(1970, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Justin",
                            HireDate = new DateTime(2014, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harris",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -82,
                            DateOfBirth = new DateTime(1963, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            HireDate = new DateTime(2000, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Young",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -83,
                            DateOfBirth = new DateTime(1974, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            HireDate = new DateTime(2013, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Alvarez",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -84,
                            DateOfBirth = new DateTime(1952, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eugene",
                            HireDate = new DateTime(2002, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Murphy",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -85,
                            DateOfBirth = new DateTime(1980, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeffrey",
                            HireDate = new DateTime(2004, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morales",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -86,
                            DateOfBirth = new DateTime(1958, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Samuel",
                            HireDate = new DateTime(2008, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Long",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -87,
                            DateOfBirth = new DateTime(1954, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jack",
                            HireDate = new DateTime(2010, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -88,
                            DateOfBirth = new DateTime(1958, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jeffrey",
                            HireDate = new DateTime(2011, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ruiz",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -89,
                            DateOfBirth = new DateTime(1966, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nicholas",
                            HireDate = new DateTime(2004, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bailey",
                            LocationID = -5
                        },
                        new
                        {
                            ID = -90,
                            DateOfBirth = new DateTime(1976, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2017, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dorothy",
                            HireDate = new DateTime(2005, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kelly",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -91,
                            DateOfBirth = new DateTime(1973, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roger",
                            HireDate = new DateTime(2007, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Green",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -92,
                            DateOfBirth = new DateTime(1977, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lauren",
                            HireDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ross",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -93,
                            DateOfBirth = new DateTime(1962, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linda",
                            HireDate = new DateTime(2004, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Clark",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -94,
                            DateOfBirth = new DateTime(1972, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Abigail",
                            HireDate = new DateTime(2013, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lee",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -95,
                            DateOfBirth = new DateTime(1978, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arthur",
                            HireDate = new DateTime(2012, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -96,
                            DateOfBirth = new DateTime(1952, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2016, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jonathan",
                            HireDate = new DateTime(2000, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ramirez",
                            LocationID = -2
                        },
                        new
                        {
                            ID = -97,
                            DateOfBirth = new DateTime(1966, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christian",
                            HireDate = new DateTime(2011, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Long",
                            LocationID = -4
                        },
                        new
                        {
                            ID = -98,
                            DateOfBirth = new DateTime(1980, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Helen",
                            HireDate = new DateTime(2010, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            LocationID = -3
                        },
                        new
                        {
                            ID = -99,
                            DateOfBirth = new DateTime(1969, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Katherine",
                            HireDate = new DateTime(2005, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rivera",
                            LocationID = -1
                        },
                        new
                        {
                            ID = -100,
                            DateOfBirth = new DateTime(1955, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            HireDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hernandez",
                            LocationID = -5
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("postalcode")
                        .HasColumnType("char(6)")
                        .HasMaxLength(6)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Address = "123 Main Street",
                            City = "Edmonton",
                            Name = "Super Duper Store",
                            PostalCode = "T6M5W2"
                        },
                        new
                        {
                            ID = -2,
                            Address = "567 Side Street",
                            City = "Vancouver",
                            Name = "Awesome Store",
                            PostalCode = "T8M2X2"
                        },
                        new
                        {
                            ID = -3,
                            Address = "246 Boulevard Street",
                            City = "Edmonton",
                            Name = "Corporate Headquarters",
                            PostalCode = "T2Y8Z2"
                        },
                        new
                        {
                            ID = -4,
                            Address = "357 Back Street",
                            City = "Calgary",
                            Name = "Silly Store",
                            PostalCode = "T9T7L2"
                        },
                        new
                        {
                            ID = -5,
                            Address = "852 Sesame Street",
                            City = "Edmonton",
                            Name = "Elmo Store",
                            PostalCode = "T9M2A9"
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Employee", b =>
                {
                    b.HasOne("_4Point1_EF.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .HasConstraintName("FK_Employee_Location")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
