// <auto-generated />
using ExistingDBPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4Point1_EF.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExistingDBPractice.Models.EmailAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("PersonID")
                        .HasColumnName("PersonID")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("PersonID")
                        .HasName("FK_EmailAddress_Person");

                    b.ToTable("emailaddress");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "johndoe@email.com",
                            PersonID = 1
                        },
                        new
                        {
                            ID = 2,
                            Email = "janedoe@email.com",
                            PersonID = 2
                        },
                        new
                        {
                            ID = 3,
                            Email = "tommywiseau@theroom.com",
                            PersonID = 3
                        },
                        new
                        {
                            ID = 4,
                            Email = "jimmysmith@email.com",
                            PersonID = 4
                        },
                        new
                        {
                            ID = 5,
                            Email = "sallysmith@email.com",
                            PersonID = 5
                        });
                });

            modelBuilder.Entity("ExistingDBPractice.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("person");
                });

            modelBuilder.Entity("ExistingDBPractice.Models.PhoneNumber", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(10)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("char(12)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("PersonID")
                        .HasColumnName("PersonID")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("PersonID")
                        .HasName("FK_PhoneNumber_Person");

                    b.ToTable("phonenumber");
                });

            modelBuilder.Entity("ExistingDBPractice.Models.EmailAddress", b =>
                {
                    b.HasOne("ExistingDBPractice.Models.Person", "Person")
                        .WithMany("Emails")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK_EmailAddress_Person")
                        .IsRequired();
                });

            modelBuilder.Entity("ExistingDBPractice.Models.PhoneNumber", b =>
                {
                    b.HasOne("ExistingDBPractice.Models.Person", "Person")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK_PhoneNumber_Person")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
